---
### A playbook for configuring a Linux node with Ansible.
# - Create bin directory and add it to the execution path
# - Create a virtual environment and install the following collections and execution environments:
#   > azure.azcollection
#   > redhat.ansible_azure_sre
#   > redhat.ansible_azure_mgmt
#   > redhat.managed_azure
#   > https://quay.io.repository/aoc/ee-aap-azure-sre (AAP Azure SRE execution environment)
# - Create an alias called "k" for the kubectl command

- name: Linux Environment Configuration
  hosts: virtualmachine
  tasks:

    - name: Print a little message
      ansible.builtin.debug:
        msg: The playbook has begun!

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#examples
    - name: Create bin directory
      ansible.builtin.file:
        path: ~/usr/bin
        state: directory
        mode: '0755'

    # https://www.jeffgeerling.com/blog/2017/add-path-global-path-ansible
    - name: Place bin in execution path
      ansible.builtin.shell: "export PATH=$PATH:/home/azureuser/usr/bin"
      become: true

        # shell script module -> export command (if above doesn't work)

    - name: Install virtualenv module
      ansible.builtin.pip:
        name: virtualenv

    - name: Create venv
      ansible.builtin.command: 
        cmd: python -m virtualenv /home/azureuser/my-venv

    - name: source the venv
      ansible.builtin.shell: source /home/azureuser/my-venv/bin/activate

    # - name: Install pip in the venv
    #  ansible.builtin.command:
    #    cmd: /home/azureuser/my-venv/bin/python -m ensurepip --upgrade

    # Install Ansible and all collections needed
    - name: Install Ansible
      ansible.builtin.pip:
        name: ansible
        virtualenv: /home/azureuser/my-venv

    - name: Install azcollection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install azure.azcollection

    - name: Install ansible_azure_sre
      ansible.builtin.command:
        cmd: ansible-galaxy collection install git@github.com:ansible/ansible-azure-sre.git

    - name: Install ansible_azure_mgmt
      ansible.builtin.command:
        cmd: ansible-galaxy collection install git@gitlab.cee.redhat.com:aoc/ansible-azure-mgmt.git

    - name: Install managed_azure
      ansible.builtin.command:
        cmd: ansible-galaxy collection install git@github.com:ansible/managed_azure.git

    - name: Create kubectl alias
      ansible.builtin.command:
        cmd: echo 'alias k="kubectl"' >> .bashrc
