---
### A playbook for configuring a Linux node with Ansible.
# - Create bin directory and add it to the execution path
# - Create a virtual environment and install the following collections and execution environments:
#   > azure.azcollection
#   > redhat.ansible_azure_sre
#   > redhat.ansible_azure_mgmt
#   > redhat.managed_azure
#   > https://quay.io.repository/aoc/ee-aap-azure-sre (AAP Azure SRE execution environment)
# - Create an alias called "k" for the kubectl command

- name: Linux Environment Configuration
  hosts: virtualmachine
  become: true
  tasks:
    - name: Print a little message
      ansible.builtin.debug:
        msg: The playbook has begun!

    # - name: Extend the home directory logical volume
    #   ansible.builtin.shell:
    #     cmd: lvextend -l +100%FREE /dev/mapper/rootvg-homelv -r
    #     creates: /home/azureuser/extended

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#examples
    - name: Create bin directory
      ansible.builtin.file:
        path: /home/azureuser/bin
        state: directory
        mode: '0755'

    # https://www.jeffgeerling.com/blog/2017/add-path-global-path-ansible
    - name: Place bin in execution path
      ansible.builtin.shell: "export PATH=$PATH:/home/azureuser/bin"

    - name: Create venv
      ansible.builtin.command:
        cmd: python3.9 -m venv /home/azureuser/my-venv
        # creates: /home/azureuser/my-venv

    - name: Source the venv
      ansible.builtin.shell: source /home/azureuser/my-venv/bin/activate

    # - name: Install pip in the venv
    #  ansible.builtin.command:
    #    cmd: /home/azureuser/my-venv/bin/python -m ensurepip --upgrade

    # Install Ansible and all collections needed
    - name: Install Ansible
      ansible.builtin.pip:
        name: ansible
        virtualenv: /home/azureuser/my-venv
        extra_args: --no-cache-dir

    # In order to clone the repositories below, Git needs to be installed:
    - name: Install Git
      ansible.builtin.dnf:
        name: git-all
        state: latest

    - name: Install azcollection
      ansible.builtin.command:
        cmd: /home/azureuser/my-venv/bin/ansible-galaxy collection install azure.azcollection -p /home/azureuser/my-venv/collections

    - name: Give rwx permissions to ansible_collections directory
      ansible.builtin.shell: chmod 777 /home/azureuser/my-venv/collections/ansible_collections

    - name: Install ansible_azure_sre
      ansible.builtin.command:
        cmd: /home/azureuser/my-venv/bin/ansible-galaxy collection install git@github.com:ansible/ansible-azure-sre.git -p /home/azureuser/my-venv/collections

    - name: Install ansible_azure_mgmt
      ansible.builtin.command:
        cmd: /home/azureuser/my-venv/bin/ansible-galaxy collection install /home/azureuser/ansible-azure-mgmt/galaxy.yml -p /home/azureuser/my-venv/collections

    - name: Install managed_azure
      ansible.builtin.command:
        cmd: /home/azureuser/my-venv/bin/ansible-galaxy collection install git@github.com:ansible/managed_azure.git -p /home/azureuser/my-venv/collections

    - name: Create kubectl alias
      ansible.builtin.command:
        cmd: echo 'alias k="kubectl"' >> .bashrc
