---
### A playbook for configuring a Linux node with Ansible.
# - Create bin directory and add it to the execution path
# - Create a virtual environment and install the following collections and execution environments:
#   > azure.azcollection
#   > redhat.ansible_azure_sre
#   > redhat.ansible_azure_mgmt
#   > redhat.managed_azure
#   > https://quay.io.repository/aoc/ee-aap-azure-sre (AAP Azure SRE execution environment)
# - Create an alias called "k" for the kubectl command

- name: Linux Environment Configuration
  hosts: linuxhost
  tasks:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#examples
    - name: Create bin directory
      ansible.builtin.file:
        path: /usr/bin
        state: directory
        mode: '0755'

    # https://www.jeffgeerling.com/blog/2017/add-path-global-path-ansible
    - name: Place bin in execution path
      ansible.builtin.copy:
        dest: /etc/profile.d/bin-to-path.sh
        content: 'PATH=$PATH:/usr/bin'

        # shell script module -> export command (if above doesn't work)

    - name: Ensure pip is installed
      ansible.builtin.command: 
        cmd: python -m ensurepip --upgrade

    - name: Create venv
      ansible.builtin.command:
          cmd: python -m venv my-venv

    - name: Source the venv # May need a different solution
      ansible.builtin.command:
        cmd: source ./my-venv/bin/activate

    # Install Ansible and all collections needed
    - name: Install Ansible
      ansible.builtin.pip:
        name: ansible
        virtualenv: ./my-venv/lib/python3.12/site-packages

    - name: Install azcollection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install azure.azcollection

    - name: Install ansible_azure_sre
      ansible.builtin.command:
        cmd: ansible-galaxy collection install git@github.com:ansible/ansible-azure-sre.git

    - name: Install ansible_azure_mgmt
      ansible.builtin.command:
        cmd: ansible-galaxy collection install git@gitlab.cee.redhat.com:aoc/ansible-azure-mgmt.git

    - name: Install managed_azure
      ansible.builtin.command:
        cmd: ansible-galaxy collection install git@github.com:ansible/managed_azure.git

    - name: Create kubectl alias
      ansible.builtin.command:
        cmd: echo 'alias k="kubectl"' >> .bashrc
