---
- name: Clean up release branches older than 30 days
  hosts: localhost
  connection: local
  gather_facts: false

  # Ideally, we want to remove branches that are timestamped
  # and older than 30 days. There is no real benefit in
  # keeping them around.

  vars:
    github_token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN', default='') }}"
    user: "{{ lookup('ansible.builtin.env', 'USER', default='aoc-saas-bot' ) }}"
    github_organization: "jacobarcarola"
    repository_base_url: "https://api.github.com/repos/{{ github_organization }}"
    max_age: 30
    current_date: "{{ now(utc=true, fmt='%Y-%m-%d') | to_datetime('%Y-%m-%d') }}"
    date_pattern: "^v[0-9]{4}-[0-9]{2}-[0-9]{2}.*"

    repos:
      - "repo1"
      - "repo2"

    # repo1 has the following branches: main, unformatted-test-branch, v2024-08-20-b98, v2024-09-06-b99, v2024-09-18-b100, v2024-09-20-b101
    # repo2 has the following branches: main, newbranch, testbranchnoformat, v2024-07-06-b123091, v2024-08-19-b112390, v2024-09-03-b12313

  tasks:
    - name: Create variable to hold headers for each API call
      ansible.builtin.set_fact:
        headers:
          Authorization: token {{ github_token }}
          X-GitHub-Api-Version: "2022-11-28"
          Accept: application/vnd.github+json


    - name: Get all branches from repo1
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ github_organization }}/repo1/branches"
        headers: "{{ headers }}"
        method: GET
        return_content: true
      register: branches

    - name: Print branches from repo1
      ansible.builtin.debug:
        msg: "Branches: {{ branches.json | map(attribute='name') | list }}"

    - name: Print only the branches that are in YYYY-MM-DD format
      ansible.builtin.debug:
        msg: "Dated branches: {{ branches.json | map(attribute='name') | map('regex_search', date_pattern) | select('string') | list }}"
      when: branches.json | map(attribute='name') | map('regex_search', date_pattern) | select('string')

    - name: Print the branches older than 30 days
      ansible.builtin.debug:
        msg: "Dated branches: {{ branches.json | map(attribute='name') | map('regex_search', date_pattern) | select('string') | list }}"
      when: (current_date - (branches.json | map(attribute='name') | map('regex_search', date_pattern) | select('string') | to_datetime('%Y-%m-%d'))).days > max_age

    - name: Print current date
      ansible.builtin.debug:
        msg: "The day is: {{ current_date }}"
